name: Create Release
on:
  push:
    branches: [master]

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version
        run: echo "VERSION=$(cat manifest.json | grep '\"version\"' | sed -e 's/\([^0-9.]\)*//g')" >> $GITHUB_ENV

      - name: Removing unnecessary files
        run: rm -r .* package.json yarn.lock *.md

      - name: Create a zip
        run: zip -r media-keys-are-for-music.zip *.* *

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          files: media-keys-are-for-music.zip
          draft: true
